[profile.default]
solc = "0.8.19"
src = 'src'
out = 'out'
libs = ['lib']
ffi = true
optimizer_runs = 1000000
evm_version = "shanghai"

[profile.integration]
no_match_path = ""
match_path = "*/integration/*"

[profile.lite.optimizer_details.yulDetails]
stackAllocation = true
optimizerSteps = 'xca'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config


fs_permissions = [
    { access = "read", path = "src/SwapRouter02Executor.huff"},
    { access = "read-write", path = ".forge-snapshots/" },
]
